server:
  port: 8100

spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.30.181:3306/achieveit?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  jackson:
    time-zone: GMT+8

logging:
  config: classpath:logback.xml

#配置邮件发送方
mail:
  user: 123400197
  password: gutlqasmyzdubjdd
  internetAddress: 123400197@qq.com


dev:
  enable: true


